-
 hosts: all
 tasks:
   - name: installing httpd
     yum: pkg=httpd state=present

   - name: restarting the service
     service: name=httpd state=restarted

   - name: deploy the application
     copy: 
       src: index.html
       dest: /var/www/html

